<a href="https://colab.research.google.com/github/khokhar002/Fun-with-data/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.random.randint(1,15,12)
print(a)
print('-------------------------')

[12 12  9  9  9  2  1 14 12 10 10  1]
-------------------------


In [ ]:
b=a.shape
print(b)

(12,)


In [ ]:
print('---------------------------')
a=a.reshape(3,4)
print(a)
print('---------------------------')

---------------------------
[[12 12  9  9]
 [ 9  2  1 14]
 [12 10 10  1]]
---------------------------


In [ ]:
a=a.reshape(6,2)
print(a)
print('---------------------------')
a=a.reshape(2,6)
print(a)
print('---------------------------')
print('---------------------------')
a=a.reshape(1,12)
print(a)
print('---------------------------')
print(a.ndim)
a=a.reshape(12)
print(a)
print('---------------------------')

[[12 12]
 [ 9  9]
 [ 9  2]
 [ 1 14]
 [12 10]
 [10  1]]
---------------------------
[[12 12  9  9  9  2]
 [ 1 14 12 10 10  1]]
---------------------------
---------------------------
[[12 12  9  9  9  2  1 14 12 10 10  1]]
---------------------------
2
[12 12  9  9  9  2  1 14 12 10 10  1]
---------------------------


In [ ]:
a=a.reshape(2,2,3)
print(a)
print('-------------------------')
print(a.ndim)
print('-------------------------')

[[[12 12  9]
  [ 9  9  2]]

 [[ 1 14 12]
  [10 10  1]]]
-------------------------
3
-------------------------


In [ ]:
a=a.reshape(4,-1)
print(a)
print('-----------------------')
a=a.reshape(6,-1)
print(a)
print('-----------------------')
a=a.reshape(2,-1)
print(a)
print('-----------------------')

[[12 12  9]
 [ 9  9  2]
 [ 1 14 12]
 [10 10  1]]
-----------------------
[[12 12]
 [ 9  9]
 [ 9  2]
 [ 1 14]
 [12 10]
 [10  1]]
-----------------------
[[12 12  9  9  9  2]
 [ 1 14 12 10 10  1]]
-----------------------


In [ ]:
a=a.reshape(-1,4)
print(a)
print('---------------------')
a=a.reshape(-1,2)
print(a)
print('---------------------')
a=a.reshape(-1,3)
print(a)

[[12 12  9  9]
 [ 9  2  1 14]
 [12 10 10  1]]
---------------------
[[12 12]
 [ 9  9]
 [ 9  2]
 [ 1 14]
 [12 10]
 [10  1]]
---------------------
[[12 12  9]
 [ 9  9  2]
 [ 1 14 12]
 [10 10  1]]
