<a href="https://colab.research.google.com/github/khokhar002/Fun-with-data/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = [[1,2,3,],[4,5,6]]
b = np.array(a)
print(b)
print()
print(b.shape)
print()
print(b.ndim)


[[1 2 3]
 [4 5 6]]

(2, 3)

2


In [ ]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [ ]:
b=np.zeros((5,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
b=np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
b=np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b=np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
b = np.eye(3,4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
b = np.diag([5,2,6,9])
print(b)

[[5 0 0 0]
 [0 2 0 0]
 [0 0 6 0]
 [0 0 0 9]]


In [ ]:
b = np.diag(b)
print(b)


[5 2 6 9]


In [ ]:
b=np.random.randint(1,10,3)
print(b)

[1 4 4]


In [ ]:
b=np.random.rand(5)
print(b)

[0.34091264 0.14112294 0.99072135 0.51095479 0.95488175]


In [ ]:
b=np.random.rand(5,2)
print(b)


[[0.29321528 0.27314347]
 [0.09517638 0.09801443]
 [0.20166169 0.09865225]
 [0.65939089 0.68779218]
 [0.89822445 0.02310029]]


In [ ]:
a=[0,1,2,3,4,5,6,7,8,9,10]
arr=np.array(a)
print(arr)
b=arr[2:9:2]
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[2 4 6 8]


In [ ]:
c=arr[:-6]
print(c)

[0 1 2 3 4]


In [ ]:
c = arr[7:]
print(c)


[ 7  8  9 10]


In [ ]:
c=arr[1:7:3]
print(c)

[1 4]


In [ ]:
c=arr[:]
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
c=arr[-5:]
print(c)

[ 6  7  8  9 10]
